### ISSUE TITLE
Question - usx2y

### ISSUE THREAD

**Issue by kholyphoenix1** [opensrc/alsa#9]
Hello, 

Needing install usx2y for Tascam 388.
How do I proceed? Could someone help me?

PS .: I'm sorry if I'm asking for help in the wrong place.
PS .: Fedora 22.

Thank you!

**Comment by markc** [comment]
Is that the Tascam 388 model with an eight-track tape?

It doesn't have a USB interface and seems to be completely analog so as long as you can connect to possible headphone i/o sockets then it should "just work".

Perhaps you mentioned the wrong model number because if you need the usx2y device then you must have a digital interface.

**Comment by kholyphoenix1** [comment]
You're right. It is an analog device.
Even messing in Tascam panel Linux does not recognize any changes to the panel in relation to the sound. I have been searching and found this guy usx2y which is used in some tascam to can use it.

**Comment by markc** [comment]
The usx2y device driver and firmware are only needed if the Tascam device
has a digital interface, like USB or firewire, if not then it does not
apply to your situation.

A question: how do you expect to capture and playback audio to and from
your linux computer, as in what type of interfaces and/or cables etc?

**Comment by kholyphoenix1** [comment]
Got it.
I do not know. The equipment is not mine is a client.
I'll see what I can do.
Thank you!
